export function renderSvg(image, entry, rendering) {
  const rectangles = pixelRuns(image)
    .map((run) => {
      const opacity =
        run.alpha === 255
          ? ""
          : ` fill-opacity="${trimNumber(run.alpha / 255)}"`;
      const fill = rendering === "silhouette" ? "currentColor" : run.color;
      return `  <rect x="${run.x}" y="${run.y}" width="${run.width}" height="1" fill="${fill}"${opacity}/>`;
    })
    .join("\n");
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${image.width} ${image.height}" shape-rendering="crispEdges">`,
    `  <title>${escapeXml(entry.name)}</title>`,
    rectangles,
    "</svg>",
    "",
  ].join("\n");
}

export function renderPreview(build) {
  const cards = build.glyphs.map(renderPreviewCard).join("\n");
  return `<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<title>${escapeXml(build.familyName)} preview</title>
<style>
  @import url("./font/pixel-emoji.css");
  @font-face {
    font-family: "${escapeCss(build.familyName)}";
    src: url("./font/pixel-emoji.woff2") format("woff2"),
         url("./font/pixel-emoji.woff") format("woff"),
         url("./font/pixel-emoji.ttf") format("truetype");
  }
  :root { color-scheme: dark; font-family: system-ui, sans-serif; }
  body { margin: 0 auto; max-width: 70rem; padding: 1rem; background: #17111d; color: #fff; }
  main { display: grid; grid-template-columns: repeat(auto-fit, minmax(18rem, 1fr)); gap: 1rem; }
  article { padding: 1rem; border: 1px solid #70458b; border-radius: .75rem; background: #25142f; }
  h1, h2 { margin-top: 0; }
  h2 { font-size: 1rem; }
  .samples { display: flex; gap: 1rem; }
  figure { margin: 0; text-align: center; }
  img, .font { display: block; width: 8rem; height: 8rem; object-fit: contain; image-rendering: pixelated; }
  .font { font: 8rem/1 "Pixel Emoji Proposed", "${escapeCss(build.familyName)}"; }
  figcaption { margin-top: .5rem; }
</style>
<h1>${escapeXml(build.familyName)} build</h1>
<p>${build.glyphCount.toLocaleString()} painted glyph${build.glyphCount === 1 ? "" : "s"}</p>
<p><a href="./atlases.html">Browse the source atlas sheets</a></p>
<main>${cards}</main>
</html>
`;
}

export function renderAtlasGallery(build, sheets) {
  const cards = sheets.map((sheet) => renderAtlasCard(sheet)).join("\n");
  return `<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width">
<title>${escapeXml(build.familyName)} atlas gallery</title>
<style>
  :root { color-scheme: dark; font-family: system-ui, sans-serif; }
  body { margin: 0 auto; max-width: 80rem; padding: 1rem; background: #17111d; color: #fff; }
  a { color: #7fd8ff; }
  main { display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 20rem), 1fr)); gap: 1rem; }
  article { min-width: 0; padding: 1rem; border: 1px solid #70458b; border-radius: .75rem; background: #25142f; }
  h1, h2 { margin-top: 0; }
  h2 { font-size: 1rem; }
  img { display: block; width: min(100%, ${build.columns * (build.cellSize + build.cellPadding * 2) + build.outerPadding * 2}px); height: auto; image-rendering: pixelated; }
</style>
<nav><a href="./index.html">Font glyph preview</a> · <a href="../../">Emoji Explorer</a></nav>
<h1>${escapeXml(build.familyName)} atlas gallery</h1>
<p>${sheets.length.toLocaleString()} painted atlas sheet${sheets.length === 1 ? "" : "s"}, grouped by Unicode category and subgroup.</p>
<main>${cards}</main>
</html>
`;
}

export function renderAtlasMarkdown(build, sheets) {
  const sections = [];
  const collectionLabels = {
    base: "Base atlases",
    "skin-tone": "Skin-tone modifier atlases",
    hair: "Hair modifier atlases",
    "skin-and-hair": "Skin-and-hair modifier atlases",
  };
  let previousCollection = "";
  let previousGroup = "";
  for (const sheet of sheets) {
    const collection = `${sheet.releaseStatus ?? "released"}:${sheet.unicodeVersion ?? ""}:${sheet.modifierType}`;
    if (collection !== previousCollection) {
      sections.push(renderCollectionHeading(build, sheet, collectionLabels));
      previousCollection = collection;
      previousGroup = "";
    }
    if (sheet.group !== previousGroup) {
      sections.push(`### ${sheet.group}`);
      previousGroup = sheet.group;
    }
    sections.push(renderMarkdownSheet(sheet));
  }
  return `# ${build.familyName} atlas gallery

[Back to the Pixel Emoji documentation](PIXEL_EMOJI.md)

This generated gallery lists every source atlas PNG that currently contains
painted artwork. The font build reads these sheets and compiles only their
nontransparent 12×12 cells.

${sheets.length.toLocaleString()} painted atlas sheet${sheets.length === 1 ? "" : "s"} are currently available.

> Generated by \`npm run pixel-font:build\`. Edit the PNG atlases rather than
> this file.

${sections.join("\n\n")}
`;
}

export function isBlackSilhouette(image) {
  let visible = false;
  for (let offset = 0; offset < image.pixels.length; offset += 4) {
    if (image.pixels[offset + 3] === 0) continue;
    visible = true;
    if (
      image.pixels[offset] !== 0 ||
      image.pixels[offset + 1] !== 0 ||
      image.pixels[offset + 2] !== 0
    )
      return false;
  }
  return visible;
}

function renderPreviewCard(glyph) {
  return `<article>
  <h2>${escapeXml(glyph.emoji)} ${escapeXml(glyph.name)}</h2>
  <div class="samples">
    ${glyph.png ? `<figure><img src="${glyph.png}" alt=""><figcaption>PNG</figcaption></figure>` : ""}
    ${glyph.svg ? `<figure><img src="${glyph.svg}" alt=""><figcaption>SVG</figcaption></figure>` : ""}
    <figure><span class="font">${escapeXml(glyph.emoji)}</span><figcaption>Font</figcaption></figure>
  </div>
  <code>${glyph.codePoints.map((point) => `U+${point}`).join(" ")}</code>
</article>`;
}

function renderAtlasCard(sheet) {
  const proposal =
    sheet.releaseStatus === "proposed"
      ? `Proposed Emoji ${escapeXml(sheet.unicodeVersion)} · `
      : "";
  const label = `${sheet.group}, ${sheet.subGroup}, part ${sheet.part} of ${sheet.partCount}`;
  return `<article>
  <h2>${escapeXml(sheet.group)} · ${escapeXml(sheet.subGroup)}${sheet.partCount > 1 ? ` · ${sheet.part}/${sheet.partCount}` : ""}</h2>
  <p>${proposal}${sheet.paintedCount.toLocaleString()} painted glyph${sheet.paintedCount === 1 ? "" : "s"}</p>
  <a href="../atlases/${escapeXml(sheet.image)}"><img src="../atlases/${escapeXml(sheet.image)}" alt="${escapeXml(label)}"></a>
  <p><a href="../atlases/${escapeXml(sheet.id)}.json">JSON cell map</a></p>
</article>`;
}

function renderCollectionHeading(build, sheet, labels) {
  const proposal = (build.proposedVersions ?? []).find(
    (version) => version.version === sheet.unicodeVersion,
  );
  const details = proposal
    ? ` (${proposal.stage ?? proposal.status}${proposal.expectedRelease ? `; expected ${proposal.expectedRelease}` : ""})`
    : "";
  const prefix =
    sheet.releaseStatus === "proposed"
      ? `Proposed Emoji ${sheet.unicodeVersion}${details} — `
      : "";
  return `## ${prefix}${labels[sheet.modifierType] ?? sheet.modifierType}`;
}

function renderMarkdownSheet(sheet) {
  const part =
    sheet.partCount > 1 ? ` — part ${sheet.part} of ${sheet.partCount}` : "";
  const label = `${sheet.group}, ${sheet.subGroup}${part}`;
  return `#### ${sheet.subGroup}${part}

[PNG](atlases/${sheet.image}) · [JSON cell map](atlases/${sheet.id}.json)

[![${label}](atlases/${sheet.image})](atlases/${sheet.image})`;
}

function pixelRuns(image) {
  const runs = [];
  for (let y = 0; y < image.height; y += 1) {
    for (let x = 0; x < image.width;) {
      const offset = (y * image.width + x) * 4;
      const [red, green, blue, alpha] = image.pixels.subarray(
        offset,
        offset + 4,
      );
      if (alpha === 0) {
        x += 1;
        continue;
      }
      let width = 1;
      while (x + width < image.width) {
        const next = (y * image.width + x + width) * 4;
        if (
          image.pixels[next] !== red ||
          image.pixels[next + 1] !== green ||
          image.pixels[next + 2] !== blue ||
          image.pixels[next + 3] !== alpha
        )
          break;
        width += 1;
      }
      runs.push({
        x,
        y,
        width,
        color: `#${hex(red)}${hex(green)}${hex(blue)}`,
        alpha,
      });
      x += width;
    }
  }
  return runs;
}

function hex(value) {
  return value.toString(16).padStart(2, "0");
}

function trimNumber(value) {
  return value.toFixed(4).replace(/0+$/, "").replace(/\.$/, "");
}

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function escapeCss(value) {
  return String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}
