---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/regaldra/public_html/github/emoji
    - /bin/cp emoji.js $DEPLOYPATH
    - /bin/cp index.css $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp LICENSE.md $DEPLOYPATH
