---
deployment:
  tasks:
    - /bin/cp emoji.js /home3/regaldra/public_html/github/emoji/
    - /bin/cp index.css /home3/regaldra/public_html/github/emoji/
    - /bin/cp index.html /home3/regaldra/public_html/github/emoji/
    - /bin/cp index.js /home3/regaldra/public_html/github/emoji/
    - /bin/cp LICENSE.md /home3/regaldra/public_html/github/emoji/
