import assert from "node:assert/strict";
import { createExplorerState } from "../src/explorer-state.js";

const first = createExplorerState();
const second = createExplorerState();

assert.deepEqual(first.allIds, []);
assert.equal(first.availableCategoryKeys.size, 0);
assert.deepEqual(first.availableGroups, []);
assert.deepEqual(first.availableSequenceTypes, []);
assert.deepEqual(first.availableSubGroups, {});
assert.deepEqual(first.byId, {});
assert.equal(first.compositionMode, "condensed");
assert.deepEqual(first.copiedEmojiKeys, []);
assert.deepEqual(first.currentEmojiCopies, {});
assert.equal(first.currentEmojiKey, "");
assert.deepEqual(first.currentDialogParentStack, []);
assert.equal(first.developerModeFromUrl, false);
assert.equal(first.explorerModeFromUrl, "");
assert.equal(first.developerModeUrlDismissed, false);
assert.deepEqual(first.emojiByKey, {});
assert.equal(first.emojiKeyByCodePoints.size, 0);
assert.deepEqual(first.dialogNavigationKeys, []);
assert.deepEqual(first.displayedKeys, []);
assert.equal(first.focusedEmojiKey, "");
assert.deepEqual(first.explorerPreferences, {});
assert.deepEqual(first.favoriteEmojiKeys, []);
assert.equal(first.groupRepresentativeEmoji.size, 0);
assert.deepEqual(first.groupedKeys, {});
assert.deepEqual(first.groups, []);
assert.deepEqual(first.items, []);
assert.equal(first.orderMode, "grouped");
assert.deepEqual(first.packageManifest, { packs: [], categories: [] });
assert.equal(first.releasedIds.size, 0);
assert.deepEqual(first.proposedVersionManifests, []);
assert.equal(first.selectedGroup, "");
assert.equal(first.selectedSequenceType, "");
assert.equal(first.selectedSubGroup, "");
assert.deepEqual(first.searchAnnotations, {});
assert.deepEqual(first.searchLabels, {});
assert.equal(first.searchLoadId, 0);
assert.deepEqual(first.searchLocales, []);
assert.deepEqual(first.searchSubgroupLabels, {});
assert.equal(first.selectedSearchLocale, "");
assert.deepEqual(first.subGroups, {});
assert.equal(first.subGroupRepresentativeEmoji.size, 0);
assert.equal(first.versionKeys.size, 0);
assert.deepEqual(first.versionManifests, []);
assert.deepEqual(first.uiStrings, {});

first.availableCategoryKeys.add("people");
first.emojiKeyByCodePoints.set("1F600", "grinningFace");
first.groupRepresentativeEmoji.set("Smileys & Emotion", "😀");
first.releasedIds.add("grinningFace");
first.subGroupRepresentativeEmoji.set("face-smiling", "😀");
first.versionKeys.set("16.0", new Set(["grinningFace"]));

assert.equal(second.availableCategoryKeys.size, 0);
assert.equal(second.emojiKeyByCodePoints.size, 0);
assert.equal(second.groupRepresentativeEmoji.size, 0);
assert.equal(second.releasedIds.size, 0);
assert.equal(second.subGroupRepresentativeEmoji.size, 0);
assert.equal(second.versionKeys.size, 0);
