import assert from 'node:assert/strict';

import {
  root,
  catalogLoader,
  demoHtml,
  demoScript,
  demoStyles,
  fontPublishWorkflow,
  pagesValidator,
  pagesWorkflow,
  pixelAtlasReadme,
  pixelEditorScript,
  pixelFontBuildCache,
  pixelFontBuildScript,
  pixelFontCompiler,
  pixelFontConfig,
  pixelFontHotReload,
  pixelFontPackager,
  pixelFontVersionScript,
  testBundleCache,
  viteConfig,
  websitePublisher
} from '../shared/unit-fixtures.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';

const pixelFontBuildOutput = await fs.readFile(
  path.join(root, 'pixel-font/scripts/build-assets/output.mjs'),
  'utf8'
);
const pixelFontBuildGlyphs = await fs.readFile(
  path.join(root, 'pixel-font/scripts/build-assets/glyphs.mjs'),
  'utf8'
);
const pixelFontBuildRenderers = await fs.readFile(
  path.join(root, 'pixel-font/scripts/build-assets/renderers.mjs'),
  'utf8'
);
const pixelFontBuildAnalysis = await fs.readFile(
  path.join(root, 'pixel-font/scripts/build-assets/analysis.mjs'),
  'utf8'
);
const pixelFontBuildContext = await fs.readFile(
  path.join(root, 'pixel-font/scripts/build-assets/context.mjs'),
  'utf8'
);
const pixelEditorRuntimeController = await fs.readFile(
  path.join(root, 'src/pixel-editor/controllers/pixel-editor-runtime.js'),
  'utf8'
);
const pixelEditorCanvasHelpers = await fs.readFile(
  path.join(root, 'src/pixel-editor/pixel-editor-canvas-helpers.js'),
  'utf8'
);
const pixelEditorFontRefreshSource = `${pixelEditorRuntimeController}\n${pixelEditorCanvasHelpers}`;

assert.match(
  pixelFontCompiler,
  /supported_variation_sequences = variation_sequences[\s\S]*if supported_variation_sequences:[\s\S]*uvs=supported_variation_sequences[\s\S]*else:[\s\S]*setupCharacterMap\(cmap\)/,
  'font compilation must not emit an invalid empty format-14 cmap table'
);
assert.match(
  demoHtml,
  /href="\.\/pixel-font\/build\/font\/pixel-emoji\.css\?v=[^"]+"[\s\S]*data-font-revision="/,
  'the demo must load the generated revisioned pixel-font stylesheet'
);
assert.ok(
  pixelFontBuildOutput.includes('createHash("sha256")') &&
    pixelFontBuildOutput.includes('path.join(context.fontDirectory, "pixel-emoji.css")') &&
    pixelFontBuildOutput.includes('url("./pixel-emoji.woff2?v=${releasedRevision}")'),
  'pixel-font builds must revision their browser font URLs'
);
assert.ok(
  pixelFontBuildOutput.includes("const releasedFamily = `Pixel Emoji ${releasedRevision}`") &&
    pixelFontBuildOutput.includes('--pixel-emoji-released-family'),
  'each rebuilt browser font must receive a unique CSS family'
);
assert.match(
  pixelFontBuildScript,
  /path\.join\(context\.workspace, "ATLASES\.md"\)[\s\S]*renderAtlasMarkdown\(manifest, paintedAtlasSheets\)/,
  'pixel-font builds must write a repository-visible Markdown atlas gallery'
);
assert.match(
  pixelFontBuildOutput + "\n" + (await fs.readFile(path.join(root, 'pixel-font/scripts/build-assets/renderers.mjs'), 'utf8')),
  /renderAtlasMarkdown[\s\S]*Generated by/,
  'pixel-font builds must identify the Markdown atlas gallery as generated'
);
assert.doesNotMatch(
  pixelAtlasReadme,
  /\d[\d,]* painted glyphs? ·/,
  'the Markdown gallery must not change whenever an existing atlas gains artwork'
);
assert.ok(
  pixelFontBuildRenderers.includes('export function isBlackSilhouette(') &&
    pixelFontBuildRenderers.includes(
      'const fill = rendering === "silhouette" ? "currentColor" : run.color;'
    ) &&
    pixelFontBuildScript.includes('silhouetteGlyphCount: glyphs.filter('),
  'black-only artwork must emit currentColor SVG silhouettes and manifest metadata'
);
assert.match(
  pixelFontCompiler,
  /silhouette_keys[\s\S]*if glyph_source\["key"\] not in silhouette_keys:[\s\S]*color_glyphs\[base_name\] = layers[\s\S]*if color_glyphs:/,
  'black-only font glyphs must remain monochrome outlines outside COLR'
);
assert.equal(
  pixelFontConfig.embeddingPermissions,
  'installable',
  'Pixel Emoji must permit installable and editable document embedding'
);
assert.match(
  pixelFontCompiler,
  /embedding_permissions[\s\S]*fsType=0[\s\S]*font_revision\(font_version\)/,
  'font compilation must apply installable embedding and the configured semantic version'
);
assert.match(
  `${pixelFontBuildScript}\n${pixelFontBuildGlyphs}`,
  /assignPrivateUseCodePoints\(glyphs\)[\s\S]*privateUseCodePoint/,
  'painted glyphs must receive atomic private-use rendering aliases'
);
assert.match(
  pixelFontCompiler,
  /private_use_cmap[\s\S]*cmap\.update\(private_use_cmap\)/,
  'the font must map atomic private-use aliases to painted glyphs'
);
assert.equal(
  pixelFontConfig.packageName,
  '@lewismoten/pixel-emoji',
  'Pixel Emoji must publish independently from the emoji data package'
);
assert.match(
  pixelFontPackager,
  /package\.template\.json[\s\S]*buildManifest\.fontVersion[\s\S]*embeddingPermissions[\s\S]*pixel-emoji-proposed-[\s\S]*renderPackageStylesheet/,
  'the font packager must validate metadata and retain separate proposed assets'
);
assert.ok(
  pixelFontBuildContext.includes('path.join(workspace, "config.json")') &&
    pixelFontBuildContext.includes('const atlasManifest = JSON.parse(') &&
    pixelFontBuildGlyphs.includes(
      'const manifest = { ...context.atlasManifest, ...context.config };'
    ),
  'font builds must use the central config as the authoritative metadata source'
);
assert.match(
  pixelFontVersionScript,
  /atlasManifestFile[\s\S]*atlasManifest\.fontVersion = config\.fontVersion[\s\S]*Promise\.all/,
  'font version bumps must keep the generated atlas manifest synchronized'
);
assert.match(
  `${pixelFontBuildScript}\n${pixelFontBuildGlyphs}`,
  /releasedCoverage[\s\S]*proposedCoverage[\s\S]*paintedGlyphCount[\s\S]*trackedGlyphCount[\s\S]*complete/,
  'the published font manifest must report released and proposed coverage by Unicode version'
);
assert.match(
  pixelFontBuildScript,
  /explorer-manifest\.json[\s\S]*fields:\s*\["key", "privateUseCodePoint", "releaseStatus"\][\s\S]*buildManifest\.glyphs\.map/,
  'font builds must emit a compact runtime manifest for the Explorer'
);
assert.match(
  fontPublishWorkflow,
  /pixel-emoji-v\*[\s\S]*npm run pixel-font:package[\s\S]*npm view[\s\S]*outputs\.publish == 'true'[\s\S]*npm publish \.\/pixel-font\/build\/package[\s\S]*gh release create[\s\S]*--repo "\$GITHUB_REPOSITORY"/,
  'font tags must publish both the standalone npm package and GitHub Release assets'
);
assert.match(
  `${pixelFontBuildScript}\n${pixelFontBuildOutput}`,
  /releasedGlyphs[\s\S]*proposedGlyphs[\s\S]*Pixel Emoji Proposed/,
  'pixel-font builds must isolate proposed artwork in a separate font'
);
assert.match(
  `${pixelFontBuildScript}\n${pixelFontBuildGlyphs}`,
  /proposedSequenceCodePoints[\s\S]*proposedSupportGlyphs[\s\S]*codePoints\.length === 1[\s\S]*proposedFontGlyphs[\s\S]*glyphs:\s*proposedFontGlyphs/,
  'proposed fonts must embed visible released components required by draft sequences'
);
assert.match(
  `${pixelFontBuildScript}\n${pixelFontBuildContext}\n${pixelFontBuildGlyphs}`,
  /--fonts-only[\s\S]*!options\.context\.fontsOnly[\s\S]*encodeRgbaPng[\s\S]*renderSvg/,
  'font-only builds must skip individual PNG and SVG glyph output'
);
assert.ok(
  pixelFontBuildContext.includes('const optimize = argv.includes("--optimize");') &&
    pixelFontBuildContext.includes(
      'const buildFingerprint = await getFontBuildFingerprint({ root, workspace });'
    ) &&
    pixelFontBuildContext.includes('return canReuseFontBuild({') &&
    pixelFontBuildScript.includes('process.exit(0);') &&
    pixelFontBuildScript.includes('await writeFontBuildState({'),
  'unchanged pixel-font sources must reuse existing build outputs before recompiling'
);
assert.match(
  pixelFontBuildCache,
  /config\.json[\s\S]*atlases[\s\S]*scripts[\s\S]*font-sequences\.test\.py[\s\S]*versions[\s\S]*state\.fingerprint !== fingerprint[\s\S]*state\.mode !== "full"[\s\S]*state\.optimize\) !== Boolean\(optimize\)/,
  'pixel-font build reuse must include atlas, generator, validation, and Unicode-version inputs'
);
assert.match(
  testBundleCache,
  /build\/tests\/integration\/package-core\.test\.mjs[\s\S]*dist\/esm\/popular\.min\.js[\s\S]*getFingerprint[\s\S]*hasCurrentBundle[\s\S]*spawnSync\(npm, \['run', 'bundle'\]/,
  'tests must reuse a complete current package build instead of regenerating it every run'
);
assert.match(
  pagesWorkflow,
  /npm run pixel-font:build -- --fonts-only --optimize/,
  'GitHub Pages deployment must build optimized fonts without individual PNG and SVG glyphs'
);
assert.match(
  pagesWorkflow,
  /npm run website:build -- --skip-build --url https:\/\/lewismoten\.github\.io\/emoji\/ --output _site/,
  'GitHub Pages must reuse the validated website builder with its project URL'
);
assert.match(
  websitePublisher,
  /https:\/\/emoji\.lewismoten\.com\/[\s\S]*npm[\s\S]*bundle[\s\S]*pixel-font:build[\s\S]*--fonts-only[\s\S]*--optimize[\s\S]*generate-demo-pages[\s\S]*generate-service-worker[\s\S]*validate-pages-site/,
  'the custom-domain website builder must compile optimized fonts and validate the Explorer'
);
assert.match(
  websitePublisher,
  /EMOJI_DEPLOY_TARGET[\s\S]*EMOJI_SSH_IDENTITY[\s\S]*EMOJI_DEPLOY_TRANSPORT[\s\S]*publishWithTar[\s\S]*tar -xzf - -C[\s\S]*--no-xattrs[\s\S]*COPYFILE_DISABLE[\s\S]*rsyncArgs[\s\S]*--checksum[\s\S]*IdentitiesOnly=yes[\s\S]*--delete-delay[\s\S]*result\.status !== 127[\s\S]*publishWithTar/,
  'website publishing must support rsync and tar-over-SSH fallback with an explicit identity'
);
assert.match(
  websitePublisher,
  /normalizeWebsitePermissions[\s\S]*chmodSync\(directory, 0o755\)[\s\S]*entry\.isDirectory\(\)[\s\S]*chmodSync\(targetPath, 0o644\)[\s\S]*normalizeWebsitePermissions\(outputDirectory\)/,
  'website publishing must make deployed directories traversable and files web-readable'
);
assert.match(
  pagesValidator,
  /CORE_ASSETS[\s\S]*replace\(\/\\\?[\s\S]*existsSync[\s\S]*Pages site is missing/,
  'Pages validation must reject a deployment with any missing precache asset'
);
assert.match(
  pagesValidator,
  /manifestFiles[\s\S]*JSON\.parse[\s\S]*has no web app manifest link[\s\S]*fontSignatures[\s\S]*wOF2/,
  'Pages validation must parse localized manifests and verify deployed web-font signatures'
);
assert.ok(
  pixelFontBuildGlyphs.includes('atlasImage: options.sheet.image,') &&
    pixelFontBuildGlyphs.includes('atlasWidth: options.mapping.imageWidth,') &&
    pixelFontBuildGlyphs.includes('x: entry.x,'),
  'font manifests must retain source atlas coordinates for browser previews'
);
assert.match(
  `${pixelFontBuildScript}\n${pixelFontBuildContext}\n${pixelFontBuildOutput}`,
  /proposedFontDirectory[\s\S]*proposed-font-source\.json/,
  'proposed font files must use a separate build directory and source'
);
assert.match(
  demoStyles,
  /--emoji-font:[\s\S]*--pixel-emoji-proposed-family[\s\S]*--pixel-emoji-released-family/,
  'the demo must use proposed, released, and system emoji as a fall-forward stack'
);
assert.match(
  viteConfig,
  /ignored: \['\*\*\/pixel-font\/build\/\*\*'\][\s\S]*server\.watcher\.add\(pixelFontRevision\)[\s\S]*pixel-font:updated[\s\S]*Cache-Control', 'no-store'/,
  'Vite must refresh completed pixel fonts without reloading the page'
);
assert.doesNotMatch(
  viteConfig,
  /type: 'full-reload'/,
  'pixel-font builds must not discard in-memory editor permissions'
);
assert.match(
  demoHtml,
  /id="pixel-font-stylesheet"[^>]*pixel-font\/build\/font\/pixel-emoji\.css\?v=[^"]+[^>]*data-font-revision="/,
  'the pixel font must use a reloadable standalone stylesheet'
);
assert.ok(
  pixelFontHotReload.includes('import.meta.hot.on') &&
    pixelFontHotReload.includes('pixel-font/font-build.revision') &&
    pixelFontHotReload.includes('refreshInFlight') &&
    pixelFontHotReload.includes('document.hidden') &&
    pixelFontHotReload.includes('window.setInterval(refresh, 5000)') &&
    pixelFontHotReload.includes('function refreshPixelFontStylesheet') &&
    pixelFontHotReload.includes("replacement.addEventListener('load'") &&
    pixelFontHotReload.includes('async function runPixelFontJobs'),
  'the demo must watch and hot-swap rebuilt pixel font assets without repainting everything in one tight polling loop'
);
assert.match(
  await fs.readFile(path.join(root, 'src/app/browser-runtime.ts'), 'utf8'),
  /onPixelFontRevisionLoaded\(\);[\s\S]*refreshExplorerPixelFont\(/,
  'the demo must hot-swap rebuilt pixel fonts without refreshing the page'
);
assert.match(
  `${catalogLoader}\n${pixelFontHotReload}`,
  /pixelFontManifestUrl = options\.isViteDevelopment[\s\S]*explorer-manifest\.json\?v=\$\{Date\.now\(\)\}[\s\S]*pixelFontRevision[\s\S]*explorer-manifest\.json\?v=\$\{pixelFontRevision\}[\s\S]*font-build\.revision[\s\S]*cache: 'no-store'/,
  'pixel font metadata loads must bypass stale development and production cache data'
);
assert.match(
  pixelFontHotReload,
  /export async function refreshExplorerPixelFont[\s\S]*build\/manifest\.json[\s\S]*options\.updateManifest\(await response\.json\(\), revision\)[\s\S]*querySelectorAll\('\[data-emoji-key\]'\)[\s\S]*options\.applyArtwork/,
  'rebuilt fonts must update existing Emoji Explorer result glyphs'
);
assert.ok(
  pixelEditorFontRefreshSource.includes('async function refreshFontBuild()') &&
    pixelEditorFontRefreshSource.includes('loadManifest(true)') &&
    pixelEditorFontRefreshSource.includes('const bypassCache = refresh || isViteDevelopment;') &&
    pixelEditorFontRefreshSource.includes('currentEntry().releaseStatus === "proposed"') &&
    pixelEditorFontRefreshSource.includes('--pixel-emoji-proposed-family') &&
    pixelEditorFontRefreshSource.includes('--pixel-emoji-released-family'),
  'the open pixel editor must reload build metadata and use the rebuilt font family'
);
assert.match(
  pixelFontBuildScript,
  /font-build\.revision[\s\S]*Date\.now\(\)/,
  'pixel-font builds must notify Vite only after generated files are ready'
);
