import type { ExplorerMusicSong } from "./explorer-audio-song-types.js";
import { NOTE_LENGTHS, PITCHES } from "./explorer-audio-notes.js";

export const lightExplorerSong: ExplorerMusicSong = {
  beatLength: 0.21,
  gain: 0.1,
  voices: [
    {
      instrument: "light-bell",
      events: [
        [PITCHES.C5, NOTE_LENGTHS.QUARTER],
        [PITCHES.E5, NOTE_LENGTHS.QUARTER],
        [PITCHES.G5, NOTE_LENGTHS.QUARTER],
        [PITCHES.A5, NOTE_LENGTHS.QUARTER, { sustain: true }],
        [PITCHES.G5, NOTE_LENGTHS.QUARTER],
        [PITCHES.E5, NOTE_LENGTHS.QUARTER],
        [PITCHES.F5, NOTE_LENGTHS.QUARTER],
        [PITCHES.G5, NOTE_LENGTHS.QUARTER],
        [PITCHES.E5, NOTE_LENGTHS.QUARTER],
        [PITCHES.C5, NOTE_LENGTHS.QUARTER],
        [PITCHES.D5, NOTE_LENGTHS.QUARTER],
        [PITCHES.E5, NOTE_LENGTHS.QUARTER],
        [PITCHES.F5, NOTE_LENGTHS.QUARTER],
        [PITCHES.G5, NOTE_LENGTHS.QUARTER],
        [PITCHES.A5, NOTE_LENGTHS.QUARTER],
        [PITCHES.B5, NOTE_LENGTHS.QUARTER, { sustain: true }],
      ],
    },
    {
      instrument: "light-pad",
      events: [
        [PITCHES.G5, NOTE_LENGTHS.QUARTER, { sustain: true }],
        [PITCHES.B5, NOTE_LENGTHS.QUARTER],
        [PITCHES.D6, NOTE_LENGTHS.QUARTER],
        [PITCHES.E6, NOTE_LENGTHS.QUARTER, { sustain: true }],
        [PITCHES.D6, NOTE_LENGTHS.QUARTER],
        [PITCHES.B5, NOTE_LENGTHS.QUARTER],
        [PITCHES.C6, NOTE_LENGTHS.QUARTER],
        [PITCHES.D6, NOTE_LENGTHS.QUARTER],
        [PITCHES.B5, NOTE_LENGTHS.QUARTER],
        [PITCHES.G5, NOTE_LENGTHS.QUARTER],
        [PITCHES.A5, NOTE_LENGTHS.QUARTER],
        [PITCHES.B5, NOTE_LENGTHS.QUARTER],
        [PITCHES.C6, NOTE_LENGTHS.QUARTER],
        [PITCHES.D6, NOTE_LENGTHS.QUARTER],
        [PITCHES.E6, NOTE_LENGTHS.QUARTER],
        [PITCHES.FS6, NOTE_LENGTHS.QUARTER, { sustain: true }],
      ],
    },
    {
      instrument: "light-bass",
      events: [
        [PITCHES.C3, NOTE_LENGTHS.HALF, { sustain: true }],
        [PITCHES.E3, NOTE_LENGTHS.HALF],
        [PITCHES.G3, NOTE_LENGTHS.HALF, { sustain: true }],
        [PITCHES.E3, NOTE_LENGTHS.HALF],
        [PITCHES.D3, NOTE_LENGTHS.HALF, { sustain: true }],
        [PITCHES.G3, NOTE_LENGTHS.HALF],
        [PITCHES.A3, NOTE_LENGTHS.HALF, { sustain: true }],
        [PITCHES.G3, NOTE_LENGTHS.HALF],
      ],
    },
    {
      instrument: "light-drums",
      events: [
        [96, NOTE_LENGTHS.QUARTER, { endFrequency: 40, releaseRatio: 0.22 }],
        [280, NOTE_LENGTHS.QUARTER, { endFrequency: 126, releaseRatio: 0.22 }],
        [150, NOTE_LENGTHS.QUARTER, { endFrequency: 67, releaseRatio: 0.22 }],
        [280, NOTE_LENGTHS.QUARTER, { endFrequency: 126, releaseRatio: 0.22 }],
        [96, NOTE_LENGTHS.QUARTER, { endFrequency: 40, releaseRatio: 0.22 }],
        [280, NOTE_LENGTHS.QUARTER, { endFrequency: 126, releaseRatio: 0.22 }],
        [150, NOTE_LENGTHS.QUARTER, { endFrequency: 67, releaseRatio: 0.22 }],
        [280, NOTE_LENGTHS.QUARTER, { endFrequency: 126, releaseRatio: 0.22 }],
        [96, NOTE_LENGTHS.QUARTER, { endFrequency: 40, releaseRatio: 0.22 }],
        [300, NOTE_LENGTHS.QUARTER, { endFrequency: 135, releaseRatio: 0.22 }],
        [150, NOTE_LENGTHS.QUARTER, { endFrequency: 67, releaseRatio: 0.22 }],
        [300, NOTE_LENGTHS.QUARTER, { endFrequency: 135, releaseRatio: 0.22 }],
        [96, NOTE_LENGTHS.QUARTER, { endFrequency: 40, releaseRatio: 0.22 }],
        [320, NOTE_LENGTHS.QUARTER, { endFrequency: 144, releaseRatio: 0.22 }],
        [150, NOTE_LENGTHS.QUARTER, { endFrequency: 67, releaseRatio: 0.22 }],
        [340, NOTE_LENGTHS.QUARTER, { endFrequency: 153, releaseRatio: 0.22 }],
      ],
    },
  ],
};
