// @ts-nocheck -- Transitional bootstrap wiring.
export function buildExplorerBootstrapShellOptions(options: any) {
  return {
    applyingUrlState: () => options.applyingUrlState(),
    copyStatus: () => options.copyStatus(),
    developerModeToggle: () => options.developerModeToggle(),
    dialog: () => options.dialog(),
    drawList: () => options.drawList(),
    emojiFontChoices: () => options.emojiFontChoices(),
    genderCheckboxes: () => options.genderCheckboxes(),
    getPixelEditor: () => options.getPixelEditor(),
    hairCheckboxes: () => options.hairCheckboxes(),
    installAppButton: () => options.installAppButton(),
    installDialog: () => options.installDialog(),
    loadVersionData: () => options.loadVersionData(),
    normalizeCodePoints: options.normalizeCodePoints,
    offlineStatus: () => options.offlineStatus(),
    orderButtons: () => options.orderButtons(),
    renderCategoryFilters: () => options.renderCategoryFilters(),
    renderSearchLanguages: () => options.renderSearchLanguages(),
    renderVersionModeToggle: () => options.renderVersionModeToggle(),
    savePreference: options.savePreference,
    savedDialog: () => options.savedDialog(),
    setDialogView: (...args: any[]) => options.setDialogView(...args),
    showEmoji: (...args: any[]) => options.showEmoji(...args),
    skinToneCheckboxes: () => options.skinToneCheckboxes(),
    state: () => options.state(),
    suppressDialogCloseSync: () => options.suppressDialogCloseSync(),
    syncUrlState: (...args: any[]) => options.syncUrlState(...args),
    syncVersionRange: () => options.syncVersionRange(),
    themeChoices: () => options.themeChoices(),
    translate: options.translate,
    urlStateReady: () => options.urlStateReady(),
    versionModeSelector: () => options.versionModeSelector(),
    versionSelector: () => options.versionSelector(),
  };
}

export function buildExplorerBootstrapControllerOptions(options: any) {
  return {
    activeFilterSummary: () => options.activeFilterSummary(),
    activeFilterText: () => options.activeFilterText(),
    animateCopy: options.animateCopy,
    applyingUrlState: () => options.applyingUrlState(),
    applyPixelArtworkClass: options.applyPixelArtworkClass,
    compactGroupChoices: () => options.compactGroupChoices(),
    compactGroupLabel: () => options.compactGroupLabel(),
    compactSequenceChoices: () => options.compactSequenceChoices(),
    compactSequenceLabel: () => options.compactSequenceLabel(),
    compactSubGroupChoices: () => options.compactSubGroupChoices(),
    compactSubGroupLabel: () => options.compactSubGroupLabel(),
    copyToClipboardValue: options.copyToClipboardValue,
    developerModeEnabled: options.developerModeEnabled,
    dialog: () => options.dialog(),
    displayExplorerLabel: options.displayExplorerLabel,
    drawList: () => options.drawList(),
    emojiList: () => options.emojiList(),
    emojiParent: () => options.emojiParent(),
    ensurePixelEditor: () => options.ensurePixelEditor(),
    focusInitialEmojiDialogAction: () =>
      options.focusInitialEmojiDialogAction(),
    formatNumber: options.formatNumber,
    getPixelEditor: () => options.getPixelEditor(),
    genderCheckboxes: () => options.genderCheckboxes(),
    genderFieldset: () => options.genderFieldset(),
    getEmojiGenders: (item: any) => options.getEmojiGenders(item),
    getExplorerSubGroup: options.getExplorerSubGroup,
    getIntroducedVersion: options.getIntroducedVersion,
    groupFilterDialog: () => options.groupFilterDialog(),
    groupPickerTrigger: () => options.groupPickerTrigger(),
    groupSelector: () => options.groupSelector(),
    hairCheckboxes: () => options.hairCheckboxes(),
    hairFieldset: () => options.hairFieldset(),
    helpDialog: () => options.helpDialog(),
    isViteDevelopment: options.isViteDevelopment,
    languageList: () => options.languageList(),
    loadPackageManifest: options.loadPackageManifest,
    matchCount: () => options.matchCount(),
    modifierFilters: () => options.modifierFilters(),
    nextRenderGeneration: () => options.nextRenderGeneration(),
    onClick: options.onClick,
    openPanel: (...args: any[]) => options.openPanel(...args),
    orderButtons: () => options.orderButtons(),
    panelDialogs: options.panelDialogs,
    recordCopiedEmoji: options.recordCopiedEmoji,
    rebuildEmojiCodePointLookup: options.rebuildEmojiCodePointLookup,
    renderCategoryFilters: () => options.renderCategoryFilters(),
    renderGeneration: () => options.renderGeneration(),
    renderSavedEmoji: options.renderSavedEmoji,
    renderVersionModeToggle: () => options.renderVersionModeToggle(),
    resetFilters: () => options.resetFilters(),
    revealExplorer: () => options.revealExplorer(),
    savePreference: options.savePreference,
    searchText: () => options.searchText(),
    sequenceTranslationKeys: options.sequenceTranslationKeys,
    sequenceTypeEmoji: options.sequenceTypeEmoji,
    sequenceTypeLabels: options.sequenceTypeLabels,
    sequenceTypeOrder: options.sequenceTypeOrder,
    sequenceTypeSelector: () => options.sequenceTypeSelector(),
    setDialogView: (...args: any[]) => options.setDialogView(...args),
    setSuppressDialogCloseSync: (value: any) =>
      options.setSuppressDialogCloseSync(value),
    showEmoji: (...args: any[]) => options.showEmoji(...args),
    skinToneCheckboxes: () => options.skinToneCheckboxes(),
    skinToneFieldset: () => options.skinToneFieldset(),
    state: () => options.state(),
    subGroupFilterDialog: () => options.subGroupFilterDialog(),
    subGroupPickerTrigger: () => options.subGroupPickerTrigger(),
    subGroupSelector: () => options.subGroupSelector(),
    suppressedPanelCloses: () => options.suppressedPanelCloses(),
    syncUrlState: (...args: any[]) => options.syncUrlState(...args),
    translate: options.translate,
    unassigned: options.unassigned,
    unicodeGroupLabelKeys: options.unicodeGroupLabelKeys,
    unicodeSubgroupLabelKeys: options.unicodeSubgroupLabelKeys,
    updateCompositionBackButton: (...args: any[]) =>
      options.updateCompositionBackButton(...args),
    updateDialogNavigation: (...args: any[]) =>
      options.updateDialogNavigation(...args),
    updateEmojiComposition: options.updateEmojiComposition,
    updateEmojiImportExamples: options.updateEmojiImportExamples,
    updateModifierArtwork: options.updateModifierArtwork,
    updatePixelArtworkManifest: options.updatePixelArtworkManifest,
    urlStateReady: () => options.urlStateReady(),
    versionModeSelector: () => options.versionModeSelector(),
    versionNext: () => options.versionNext(),
    versionPrevious: () => options.versionPrevious(),
    versionRange: () => options.versionRange(),
    versionRangeValue: () => options.versionRangeValue(),
    versionSelector: () => options.versionSelector(),
  };
}

export function buildExplorerBootstrapRuntimeSourceOptions(options: any) {
  return {
    advancedFilters: () => options.advancedFilters(),
    applyingUrlState: () => options.applyingUrlState(),
    applyBasicUrlState: options.applyBasicUrlState,
    applyDialogUrlState: options.applyDialogUrlState,
    applyPixelArtworkClass: options.applyPixelArtworkClass,
    applyStandalonePixelArtwork: options.applyStandalonePixelArtwork,
    bindAudioInteractions: options.bindAudioInteractions,
    clearFiltersButton: () => options.clearFiltersButton(),
    copyStatus: () => options.copyStatus(),
    developerModeEnabled: options.developerModeEnabled,
    developerModeToggle: () => options.developerModeToggle(),
    displayGroupName: options.displayGroupName,
    displayUnicodeSubGroupName: options.displayUnicodeSubGroupName,
    drawList: (...args: any[]) => options.drawList(...args),
    emojiFontChoices: () => options.emojiFontChoices(),
    emojiList: () => options.emojiList(),
    genderCheckboxes: () => options.genderCheckboxes(),
    focusInitialEmojiDialogAction: options.focusInitialEmojiDialogAction,
    getIntroducedVersion: options.getIntroducedVersion,
    getPixelEditor: () => options.getPixelEditor(),
    getPixelEditorPromise: () => options.getPixelEditorPromise(),
    groupFilterDialog: () => options.groupFilterDialog(),
    groupPickerTrigger: () => options.groupPickerTrigger(),
    groupSelector: () => options.groupSelector(),
    hairCheckboxes: () => options.hairCheckboxes(),
    helpDialog: () => options.helpDialog(),
    helpPicker: () => options.helpPicker(),
    installApp: options.installApp,
    installAppButton: () => options.installAppButton(),
    installDialog: () => options.installDialog(),
    languageDialog: () => options.languageDialog(),
    languageList: () => options.languageList(),
    languagePicker: () => options.languagePicker(),
    languagePickerFlag: () => options.languagePickerFlag(),
    languagePickerLabel: () => options.languagePickerLabel(),
    loadData: options.loadData,
    loadSearchLanguages: () => options.loadSearchLanguages(),
    loadUiTranslations: options.loadUiTranslations,
    matchCount: () => options.matchCount(),
    navigateEmoji: (amount: number) => options.navigateEmoji(amount),
    nextSearchLoadId: () => options.nextSearchLoadId(),
    onClick: options.onClick,
    onCompactChoiceKeyDown: options.onCompactChoiceKeyDown,
    onDocumentKeyDown: options.onDocumentKeyDown,
    onEmojiDialogClick: options.onEmojiDialogClick,
    onEmojiDialogClose: options.onEmojiDialogClose,
    onEmojiFocus: options.onEmojiFocus,
    onEmojiKeyDown: options.onEmojiKeyDown,
    onGenderChange: options.onGenderChange,
    onOrderModeChange: options.onOrderModeChange,
    onVersionRangeInput: options.onVersionRangeInput,
    openFilterPicker: options.openFilterPicker,
    orderButtons: () => options.orderButtons(),
    panelDialogs: options.panelDialogs,
    populateVersionModeOptions: (...args: any[]) =>
      options.populateVersionModeOptions(...args),
    refreshLocalizedLabels: options.refreshLocalizedLabels,
    resetFilters: () => options.resetFilters(),
    renderCategoryFilters: (...args: any[]) =>
      options.renderCategoryFilters(...args),
    renderDeveloperMode: options.renderDeveloperMode,
    renderInstallAppButton: options.renderInstallAppButton,
    renderPixelFontToggle: options.renderPixelFontToggle,
    renderSavedEmoji: options.renderSavedEmoji,
    renderThemeToggle: options.renderThemeToggle,
    renderVersionModeToggle: () => options.renderVersionModeToggle(),
    restoreDeveloperMode: options.restoreDeveloperMode,
    savePreference: options.savePreference,
    savedDialog: () => options.savedDialog(),
    savedPicker: () => options.savedPicker(),
    scheduleSearchDraw: options.scheduleSearchDraw,
    searchText: () => options.searchText(),
    selectEmojiFont: options.selectEmojiFont,
    selectTheme: options.selectTheme,
    setApplyingUrlState: options.setApplyingUrlState,
    setControls: options.setControls,
    setDialogView: (...args: any[]) => options.setDialogView(...args),
    setElements: options.setElements,
    setFieldsets: options.setFieldsets,
    setPixelEditor: options.setPixelEditor,
    setPixelEditorPromise: options.setPixelEditorPromise,
    setSearchLanguage: options.setSearchLanguage,
    setSuppressDialogCloseSync: options.setSuppressDialogCloseSync,
    setUrlStateReady: options.setUrlStateReady,
    showEmoji: (...args: any[]) => options.showEmoji(...args),
    skinToneCheckboxes: () => options.skinToneCheckboxes(),
    stepVersion: options.stepVersion,
    state: () => options.state(),
    subGroupFilterDialog: () => options.subGroupFilterDialog(),
    subGroupPickerTrigger: () => options.subGroupPickerTrigger(),
    subGroupSelector: () => options.subGroupSelector(),
    suppressedPanelCloses: () => options.suppressedPanelCloses(),
    syncUrlState: (...args: any[]) => options.syncUrlState(...args),
    syncVersionRange: (...args: any[]) => options.syncVersionRange(...args),
    themeChoices: () => options.themeChoices(),
    toggleDeveloperMode: options.toggleDeveloperMode,
    toggleVersionMode: (...args: any[]) => options.toggleVersionMode(...args),
    toolbar: () => options.toolbar(),
    translate: options.translate,
    updateCompositionBackButton: (...args: any[]) =>
      options.updateCompositionBackButton(...args),
    updateDialogNavigation: (...args: any[]) =>
      options.updateDialogNavigation(...args),
    updateEmojiComposition: options.updateEmojiComposition,
    updateFavoriteButton: options.updateFavoriteButton,
    updateModifierArtwork: options.updateModifierArtwork,
    updateOnlineStatus: options.updateOnlineStatus,
    updatePixelArtworkManifest: options.updatePixelArtworkManifest,
    updateRenderingDiagnostic: options.updateRenderingDiagnostic,
    urlStateReady: () => options.urlStateReady(),
    versionModeSelector: () => options.versionModeSelector(),
    versionModeToggle: () => options.versionModeToggle(),
    versionNext: () => options.versionNext(),
    versionPrevious: () => options.versionPrevious(),
    versionRange: () => options.versionRange(),
    versionSelector: () => options.versionSelector(),
  };
}
