// @ts-nocheck -- Transitional bootstrap wiring.
export function buildExplorerBootstrapRuntimeOptions(options: any) {
  return {
    activeFilters: () => options.advancedFilters(),
    advancedFilters: () => options.advancedFilters(),
    advancedFiltersButton: () => options.advancedFiltersButton(),
    applyingUrlState: () => options.applyingUrlState(),
    applyBasicUrlState: options.applyBasicUrlState,
    applyDialogUrlState: options.applyDialogUrlState,
    applyPixelArtworkClass: options.applyPixelArtworkClass,
    applyStandalonePixelArtwork: options.applyStandalonePixelArtwork,
    bindAudioInteractions: options.bindAudioInteractions,
    clearFiltersButton: () => options.clearFiltersButton(),
    copyStatus: () => options.copyStatus(),
    developerModeEnabled: options.developerModeEnabled,
    developerModeToggle: () => options.developerModeToggle(),
    displayGroupName: options.displayGroupName,
    displayUnicodeSubGroupName: options.displayUnicodeSubGroupName,
    drawList: (...args: any[]) => options.drawList(...args),
    emojiFontChoices: () => options.emojiFontChoices(),
    emojiList: () => options.emojiList(),
    genderCheckboxes: () => options.genderCheckboxes(),
    focusInitialEmojiDialogAction: options.focusInitialEmojiDialogAction,
    getIntroducedVersion: options.getIntroducedVersion,
    getPixelEditor: () => options.getPixelEditor(),
    getPixelEditorPromise: () => options.getPixelEditorPromise(),
    groupFilterDialog: () => options.groupFilterDialog(),
    groupPickerTrigger: () => options.groupPickerTrigger(),
    groupSelector: () => options.groupSelector(),
    hairCheckboxes: () => options.hairCheckboxes(),
    helpDialog: () => options.helpDialog(),
    helpPicker: () => options.helpPicker(),
    installApp: options.installApp,
    installAppButton: () => options.installAppButton(),
    installDialog: () => options.installDialog(),
    languageDialog: () => options.languageDialog(),
    languageList: () => options.languageList(),
    languagePicker: () => options.languagePicker(),
    languagePickerFlag: () => options.languagePickerFlag(),
    languagePickerLabel: () => options.languagePickerLabel(),
    loadData: options.loadData,
    loadSearchLanguages: () => options.loadSearchLanguages(),
    loadUiTranslations: options.loadUiTranslations,
    matchCount: () => options.matchCount(),
    navigateEmoji: (amount: number) => options.navigateEmoji(amount),
    nextSearchLoadId: () => options.nextSearchLoadId(),
    onClick: options.onClick,
    onCompactChoiceKeyDown: options.onCompactChoiceKeyDown,
    onDocumentKeyDown: options.onDocumentKeyDown,
    onEmojiDialogClick: options.onEmojiDialogClick,
    onEmojiDialogClose: options.onEmojiDialogClose,
    onEmojiFocus: options.onEmojiFocus,
    onHairChange: options.onHairChange,
    onEmojiKeyDown: options.onEmojiKeyDown,
    onGenderChange: options.onGenderChange,
    onSkinToneChange: options.onSkinToneChange,
    onOrderModeChange: options.onOrderModeChange,
    onVersionRangeInput: options.onVersionRangeInput,
    openFilterPicker: options.openFilterPicker,
    orderButtons: () => options.orderButtons(),
    panelDialogs: options.panelDialogs,
    populateVersionModeOptions: (...args: any[]) =>
      options.populateVersionModeOptions(...args),
    refreshLocalizedLabels: options.refreshLocalizedLabels,
    renderCategoryFilters: (...args: any[]) =>
      options.renderCategoryFilters(...args),
    renderDeveloperMode: options.renderDeveloperMode,
    renderInstallAppButton: options.renderInstallAppButton,
    renderPixelFontToggle: options.renderPixelFontToggle,
    renderSavedEmoji: options.renderSavedEmoji,
    renderThemeToggle: options.renderThemeToggle,
    renderVersionModeToggle: () => options.renderVersionModeToggle(),
    resetFilters: () => options.resetFilters(),
    restoreDeveloperMode: options.restoreDeveloperMode,
    savePreference: options.savePreference,
    savedDialog: () => options.savedDialog(),
    savedPicker: () => options.savedPicker(),
    scheduleSearchDraw: options.scheduleSearchDraw,
    searchText: () => options.searchText(),
    selectEmojiFont: options.selectEmojiFont,
    selectTheme: options.selectTheme,
    setApplyingUrlState: options.setApplyingUrlState,
    setControls: options.setControls,
    setDialogView: (...args: any[]) => options.setDialogView(...args),
    setElements: options.setElements,
    setFieldsets: options.setFieldsets,
    setPixelEditor: options.setPixelEditor,
    setPixelEditorPromise: options.setPixelEditorPromise,
    setSearchLanguage: options.setSearchLanguage,
    setSuppressDialogCloseSync: options.setSuppressDialogCloseSync,
    setUrlStateReady: options.setUrlStateReady,
    showEmoji: (...args: any[]) => options.showEmoji(...args),
    skinToneCheckboxes: () => options.skinToneCheckboxes(),
    stepVersion: options.stepVersion,
    state: () => options.state(),
    subGroupFilterDialog: () => options.subGroupFilterDialog(),
    subGroupPickerTrigger: () => options.subGroupPickerTrigger(),
    subGroupSelector: () => options.subGroupSelector(),
    suppressedPanelCloses: () => options.suppressedPanelCloses(),
    syncUrlState: (...args: any[]) => options.syncUrlState(...args),
    syncVersionRange: (...args: any[]) => options.syncVersionRange(...args),
    themeChoices: () => options.themeChoices(),
    toggleDeveloperMode: options.toggleDeveloperMode,
    toggleVersionMode: (...args: any[]) => options.toggleVersionMode(...args),
    toolbar: () => options.toolbar(),
    translate: options.translate,
    updateCompositionBackButton: (...args: any[]) =>
      options.updateCompositionBackButton(...args),
    updateDialogNavigation: (...args: any[]) =>
      options.updateDialogNavigation(...args),
    updateEmojiComposition: options.updateEmojiComposition,
    updateFavoriteButton: options.updateFavoriteButton,
    updateModifierArtwork: options.updateModifierArtwork,
    updateOnlineStatus: options.updateOnlineStatus,
    updatePixelArtworkManifest: options.updatePixelArtworkManifest,
    updateRenderingDiagnostic: options.updateRenderingDiagnostic,
    urlStateReady: () => options.urlStateReady(),
    versionModeSelector: () => options.versionModeSelector(),
    versionModeToggle: () => options.versionModeToggle(),
    versionNext: () => options.versionNext(),
    versionPrevious: () => options.versionPrevious(),
    versionRange: () => options.versionRange(),
    versionSelector: () => options.versionSelector(),
  };
}
