import {
  bindExplorerEvents,
  finalizeExplorerStartup,
  initializeExplorerControls,
} from "../explorer-app.js";
import { createFilterControlSetup } from "../explorer/filter-controls.js";
import { observeToolbarHeight } from "../explorer/toolbar-layout.js";
import {
  closePanelDialog,
  installedDisplayQueries,
  openPanelDialog,
} from "../explorer/pwa-panels.js";
import { createStartupOrchestrator } from "./startup-orchestrator.js";

export function createStartupRuntime(options: any) {
  return createStartupOrchestrator({
    advancedFilters: () => options.advancedFilters(),
    advancedFiltersButton: () => options.advancedFiltersButton(),
    applyingUrlState: () => options.applyingUrlState(),
    applyBasicUrlState: options.applyBasicUrlState,
    applyDialogUrlState: options.applyDialogUrlState,
    applyPixelArtworkClass: options.applyPixelArtworkClass,
    bindAudioInteractions: options.bindAudioInteractions,
    assignControls: options.assignControls,
    assignElements: options.assignElements,
    assignModifierFieldsets: options.assignModifierFieldsets,
    bindEvents: bindExplorerEvents,
    clearFiltersButton: () => options.clearFiltersButton(),
    closePanel: closePanelDialog,
    copiedEmojiKeys: () => options.copiedEmojiKeys(),
    createFilterControlSetup,
    developerModeToggle: () => options.developerModeToggle(),
    dialog: () => options.dialog(),
    drawList: (...args: any[]) => options.drawList(...args),
    emojiByKey: () => options.emojiByKey(),
    emojiFontChoices: () => options.emojiFontChoices(),
    emojiList: () => options.emojiList(),
    emojiNext: () => options.emojiNext(),
    emojiPrevious: () => options.emojiPrevious(),
    favoriteEmojiKeys: () => options.favoriteEmojiKeys(),
    finalizeStartup: finalizeExplorerStartup,
    genderCheckboxes: () => options.genderCheckboxes(),
    groupFilterDialog: () => options.groupFilterDialog(),
    groupPickerTrigger: () => options.groupPickerTrigger(),
    groupSelector: () => options.groupSelector(),
    hairCheckboxes: () => options.hairCheckboxes(),
    helpDialog: () => options.helpDialog(),
    helpPicker: () => options.helpPicker(),
    hideModifierEmojiAccessibility: options.hideModifierEmojiAccessibility,
    initializeControls: initializeExplorerControls,
    installApp: options.installApp,
    installAppButton: () => options.installAppButton(),
    installDialog: () => options.installDialog(),
    installedDisplayQueries,
    languageDialog: () => options.languageDialog(),
    languageList: () => options.languageList(),
    languagePicker: () => options.languagePicker(),
    loadData: options.loadData,
    loadSearchLanguages: () => options.loadSearchLanguages(),
    loadUiTranslations: options.loadUiTranslations,
    matchCount: () => options.matchCount(),
    navigateEmoji: (amount: number) => options.navigateEmoji(amount),
    observeToolbarHeight,
    onClick: options.onClick,
    onCompactChoiceKeyDown: options.onCompactChoiceKeyDown,
    onDocumentKeyDown: options.onDocumentKeyDown,
    onEmojiDialogClick: options.onEmojiDialogClick,
    onEmojiDialogClose: options.onEmojiDialogClose,
    onEmojiFocus: options.onEmojiFocus,
    onHairChange: options.onHairChange,
    onEmojiKeyDown: options.onEmojiKeyDown,
    onGenderChange: options.onGenderChange,
    onSkinToneChange: options.onSkinToneChange,
    onOrderModeChange: options.onOrderModeChange,
    onPanelClose: options.onPanelClose,
    onVersionRangeInput: options.onVersionRangeInput,
    openFilterPicker: options.openFilterPicker,
    openPanel: openPanelDialog,
    orderButtons: () => options.orderButtons(),
    panelDialogs: options.panelDialogs,
    populateVersionModeOptions: (...args: any[]) =>
      options.populateVersionModeOptions(...args),
    positionFavoriteButton: options.positionFavoriteButton,
    preferences: () => options.preferences(),
    renderDeveloperMode: options.renderDeveloperMode,
    renderInstallAppButton: options.renderInstallAppButton,
    renderPixelFontToggle: options.renderPixelFontToggle,
    renderSavedEmoji: options.renderSavedEmoji,
    renderThemeToggle: options.renderThemeToggle,
    renderVersionModeToggle: () => options.renderVersionModeToggle(),
    resolveElements: () => options.resolveElements(),
    resetFilters: () => options.resetFilters(),
    savePreference: options.savePreference,
    savedDialog: () => options.savedDialog(),
    savedPicker: () => options.savedPicker(),
    scheduleSearchDraw: options.scheduleSearchDraw,
    searchText: () => options.searchText(),
    selectEmojiFont: options.selectEmojiFont,
    selectTheme: options.selectTheme,
    setUrlStateReady: options.setUrlStateReady,
    showEmoji: (...args: any[]) => options.showEmoji(...args),
    skinToneCheckboxes: () => options.skinToneCheckboxes(),
    stepVersion: options.stepVersion,
    subGroupFilterDialog: () => options.subGroupFilterDialog(),
    subGroupPickerTrigger: () => options.subGroupPickerTrigger(),
    subGroupSelector: () => options.subGroupSelector(),
    suppressedPanelCloses: () => options.suppressedPanelCloses(),
    syncUrlState: (...args: any[]) => options.syncUrlState(...args),
    syncVersionRange: (...args: any[]) => options.syncVersionRange(...args),
    themeChoices: () => options.themeChoices(),
    toggleDeveloperMode: options.toggleDeveloperMode,
    toggleVersionMode: (...args: any[]) => options.toggleVersionMode(...args),
    toolbar: () => options.toolbar(),
    updateOnlineStatus: options.updateOnlineStatus,
    urlStateReady: () => options.urlStateReady(),
    versionModeSelector: () => options.versionModeSelector(),
    versionModeToggle: () => options.versionModeToggle(),
    versionNext: () => options.versionNext(),
    versionPrevious: () => options.versionPrevious(),
    versionRange: () => options.versionRange(),
    versionSelector: () => options.versionSelector(),
  });
}
