export const languageFlags: Record<string, string> = {
  ar: "🇸🇦",
  en: "🇺🇸",
  "en-GB": "🇬🇧",
  "en-x-newspeak": "👁️",
  "en-US": "🇺🇸",
  es: "🇪🇸",
  hi: "🇮🇳",
  "hi-IN": "🇮🇳",
  zh: "🇨🇳",
  "zh-CN": "🇨🇳",
};

export const unicodeGroupLabelKeys: Record<string, string> = {
  Activities: "activities",
  "Animals & Nature": "animals_nature",
  Component: "emoji",
  Flags: "flags",
  "Food & Drink": "food_drink",
  Objects: "objects",
  "People & Body": "person",
  "Smileys & Emotion": "smileys_people",
  Symbols: "symbols",
  "Travel & Places": "travel_places",
};

export const unicodeSubgroupLabelKeys: Record<string, string> = {
  "animal-amphibian": "animal",
  "animal-bird": "animal",
  "animal-bug": "animal",
  "animal-mammal": "animal",
  "animal-marine": "animal",
  "animal-reptile": "animal",
  arrow: "arrows",
  "arts & crafts": "activities",
  "award-medal": "activities",
  "body-parts": "body",
  "cat-face": "smiley",
  clothing: "person",
  "country-flag": "flags",
  drink: "food_drink",
  emotion: "heart",
  "face-affection": "smiley",
  "face-concerned": "smiley",
  "face-costume": "smiley",
  "face-glasses": "smiley",
  "face-hand": "smiley",
  "face-hat": "smiley",
  "face-negative": "smiley",
  "face-neutral-skeptical": "smiley",
  "face-sleepy": "smiley",
  "face-smiling": "smiley",
  "face-tongue": "smiley",
  "face-unwell": "smiley",
  flag: "flags",
  "food-asian": "food_drink",
  "food-fruit": "food_drink",
  "food-prepared": "food_drink",
  "food-sweet": "food_drink",
  "food-vegetable": "food_drink",
  game: "sport",
  geometric: "geometric_shapes",
  "hand-fingers-closed": "body",
  "hand-fingers-open": "body",
  "hand-fingers-partial": "body",
  "hand-prop": "body",
  "hand-single-finger": "body",
  hands: "body",
  "hair-style": "person",
  heart: "heart",
  keycap: "keycap",
  "monkey-face": "animal",
  music: "musical_symbols",
  "musical-instrument": "musical_symbols",
  person: "person",
  "person-activity": "person",
  "person-fantasy": "person",
  "person-gesture": "person",
  "person-resting": "person",
  "person-role": "person",
  "person-sport": "person",
  "place-building": "place",
  "place-geographic": "place",
  "place-map": "place",
  "place-other": "place",
  "place-religious": "place",
  "plant-flower": "plant",
  "plant-other": "plant",
  "skin-tone": "modifier",
  "sky & weather": "weather",
  sport: "sport",
  "subdivision-flag": "flags",
  "transport-air": "travel",
  "transport-ground": "travel",
  "transport-sign": "travel",
  "transport-water": "travel",
};

export const sequenceTypeLabels: Record<string, string> = {
  single: "Single emoji",
  modifier: "Modifier sequences",
  zwj: "ZWJ sequences",
  flag: "Flags",
  keycap: "Keycap sequences",
  tag: "Tag sequences",
};

export const sequenceTypeOrder = Object.keys(sequenceTypeLabels);

export const sequenceTranslationKeys: Record<string, string> = {
  single: "sequenceSingle",
  modifier: "sequenceModifier",
  zwj: "sequenceZwj",
  flag: "sequenceFlag",
  keycap: "sequenceKeycap",
  tag: "sequenceTag",
};

export const sequenceTypeEmoji: Record<string, string> = {
  single: "😀",
  modifier: "👋🏽",
  zwj: "👨‍👩‍👧",
  flag: "🏳️",
  keycap: "#️⃣",
  tag: "🏴",
};

export const statusTranslationKeys: Record<string, string> = {
  "fully-qualified": "fullyQualified",
  "minimally-qualified": "minimallyQualified",
  unqualified: "unqualified",
};

export const explorerLabelKeys: Record<string, string> = {
  Africa: "africa",
  Asia: "asia",
  Europe: "europe",
  "North America": "northAmerica",
  "South America": "southAmerica",
  Oceania: "oceania",
  "Other Flags": "otherFlags",
  Accessories: "accessories",
  Clothing: "clothing",
  "Hats & Headwear": "hatsHeadwear",
  Shoes: "shoes",
  "Couples with Heart": "couplesWithHeart",
  Families: "families",
  "Holding Hands": "holdingHands",
  "Kissing Couples": "kissingCouples",
  Adults: "adults",
  Children: "children",
};

export const versionModeDefinitions = [
  {
    value: "through",
    key: "throughSelectedVersion",
    fallback: "All up to selected version",
  },
  {
    value: "selected",
    key: "selectedVersionOnly",
    fallback: "Selected version only",
  },
] as const;
