import {
  allIds,
  availableCategoryKeys,
  availableGroups,
  availableSequenceTypes,
  availableSubGroups,
  byId,
  compositionMode,
  copiedEmojiKeys,
  currentDialogParentStack,
  currentEmojiCopies,
  currentEmojiKey,
  developerModeFromUrl,
  developerModeUrlDismissed,
  dialogNavigationKeys,
  displayedKeys,
  emojiByKey,
  emojiKeyByCodePoints,
  explorerModeFromUrl,
  favoriteEmojiKeys,
  focusedEmojiKey,
  groupedKeys,
  groupRepresentativeEmoji,
  groups,
  items,
  orderMode,
  packageManifest,
  proposedVersionManifests,
  releasedIds,
  searchAnnotations,
  searchLabels,
  searchLoadId,
  searchLocales,
  searchSubgroupLabels,
  selectedGroup,
  selectedSearchLocale,
  selectedSequenceType,
  selectedSubGroup,
  subGroupRepresentativeEmoji,
  subGroups,
  versionKeys,
  versionManifests,
} from "./state.js";

export function createExplorerState() {
  return {
    allIds: [],
    availableCategoryKeys: new Set(availableCategoryKeys.get()),
    availableGroups: [...availableGroups.get()],
    availableSequenceTypes: [...availableSequenceTypes.get()],
    availableSubGroups: { ...availableSubGroups.get() },
    byId: { ...byId.get() },
    compositionMode: compositionMode.get(),
    copiedEmojiKeys: [...copiedEmojiKeys.get()],
    currentDialogParentStack: [...currentDialogParentStack.get()],
    currentEmojiCopies: { ...currentEmojiCopies.get() },
    currentEmojiKey: currentEmojiKey.get(),
    developerModeFromUrl: developerModeFromUrl.get(),
    developerModeUrlDismissed: developerModeUrlDismissed.get(),
    dialogNavigationKeys: [...dialogNavigationKeys.get()],
    displayedKeys: [...displayedKeys.get()],
    emojiByKey: { ...emojiByKey.get() },
    emojiKeyByCodePoints: new Map(emojiKeyByCodePoints.get()),
    explorerModeFromUrl: explorerModeFromUrl.get() ?? "",
    favoriteEmojiKeys: [...favoriteEmojiKeys.get()],
    focusedEmojiKey: focusedEmojiKey.get(),
    groupedKeys: { ...groupedKeys.get() },
    groupRepresentativeEmoji: new Map(groupRepresentativeEmoji.get()),
    groups: [...groups.get()],
    items: [...items.get()],
    orderMode: orderMode.get(),
    packageManifest: packageManifest.get(),
    proposedVersionManifests: [...proposedVersionManifests.get()],
    releasedIds: new Set(releasedIds.get()),
    searchAnnotations: { ...searchAnnotations.get() },
    searchLabels: { ...searchLabels.get() },
    searchLoadId: searchLoadId.get(),
    searchLocales: [...searchLocales.get()],
    searchSubgroupLabels: { ...searchSubgroupLabels.get() },
    selectedGroup: selectedGroup.get(),
    selectedSearchLocale: selectedSearchLocale.get(),
    selectedSequenceType: selectedSequenceType.get(),
    selectedSubGroup: selectedSubGroup.get(),
    subGroupRepresentativeEmoji: new Map(subGroupRepresentativeEmoji.get()),
    subGroups: { ...subGroups.get() },
    versionKeys: new Map(versionKeys.get()),
    versionManifests: [...versionManifests.get()],
  };
}
