name: Delete Package Versions

on:
  push:
    branches:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    name: Remove Prior Version
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/delete-package-versions@v1
        with:
          owner: "lewismoten"
          repo: "emoji"
          package-name: "emoji"
          num-old-versions-to-delete: 100
          token: ${{ secrets.GITHUB_TOKEN }}
