name: Delete Package Versions

on:
  push:
    branches-ignore:
      - "**"

jobs:
  delete:
    runs-on: ubuntu-latest
    name: Remove Old Versions
    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.3.2
        with:
          owner: "lewismoten"
          repo: "emoji"
          names: emoji
