name: Delete Package Versions

on:
  push:
    branches:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    name: Delete Old Packages
    steps:
      - uses: actions/delete-package-versions@v1
        with:
        package-version-ids:
        owner: lewismoten
        repo: emoji
        package-name: "@lewismoten/emoji"
        num-old-versions-to-delete: 10
        token: ${{secrets.GITHUB_TOKEN}}
